language: node_js
node_js:
  - "8"
  - "10"
services:
  - redis-server  
cache:  
  directories:
    - "node_modules"
env:
  - NODE_ENV=production
install:
  - npm install
script:
  - npm run lint
  - npm test